site_name: CSCT Think Tank
theme:
  name: material
nav: 
  - Home : 'index.md'
  - What we do :
    - Committees : './do/committees.md'
    - Events : './do/events.md'
    - Releases : './do/releases.md'
  - How we work :
    - Committees : './do/committees.md'
    - Formation of committees : './do/events.md'
    - Releases : './do/releases.md'
  - Organisational Structure : './structure.md'
  - secretariat:
    - General Seceratary: './secretariat/SG.md'
    - Secretary of Commitee Formation : './secretariat/SCF.md'
    - Secretary of Commitee Operations : './secretariat/SCO.md'
    - Secretary of Fellowship : './secretariat/SF.md'
    - Secretary of Website : './secretariat/SW.md'
  - List of Commitees :
    - AI Committee : './committees/AI.md'
    - Game Development Committee : './committees/Game-dev.md'
    - Chatbot Committee : './committees/Chatbot.md'
    - AI in LS Committee : './committees/AI-in-LS.md'
    - Programming Language Committee : './committees/Programming-Language.md'